### PR TITLE
feat: upgrade to Angular 13 and switch to modern APF

### PR DESCRIPTION
**Pull request by arturovt**

### CODE REVIEW

**Comment by arturovt** [comment]
Awaiting this to be released: https://github.com/ngneat/overview/pull/9

**Comment by shhdharmen** [comment]
Please raise PR to `beta` branch.

**Comment by NetanelBasal** [comment]
https://github.com/ngneat/overview/issues/10

**Comment by arturovt** [comment]
@shhdharmen friendly ping. Could you publish a beta version?

**Review by shhdharmen — APPROVED** [review]
LGTM

**Pull request merged**
